
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package aplicacioncliente;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ELIMINAR_COMPONENTE = 22;
  public static final int ELIMINAR_FORMULARIO = 19;
  public static final int NUEVO_FORMULARIO = 18;
  public static final int INFO = 13;
  public static final int MODIFICAR_COMPONENTE = 23;
  public static final int CUALQUIER_COSA_CON_ESPACIOS = 25;
  public static final int FIN_RESPUESTA = 10;
  public static final int INICIO_RESPUESTA = 9;
  public static final int MAYOR_QUE = 3;
  public static final int ELIMINAR_USUARIO = 16;
  public static final int CREAR_USUARIO = 14;
  public static final int DOS_PUNTOS = 5;
  public static final int LLAVE_ABIERTA = 7;
  public static final int COMA = 6;
  public static final int MENOR_QUE = 2;
  public static final int EOF = 0;
  public static final int AGREGAR_COMPONENTE = 21;
  public static final int FIN_RESPUESTAS = 12;
  public static final int ERROR_PARAMETRO = 24;
  public static final int error = 1;
  public static final int LOGIN_USUARIO = 17;
  public static final int SIGNO_INTERROGACION = 4;
  public static final int CUALQUIER_COSA_SIN_ESPACIOS = 26;
  public static final int MODIFICAR_FORMULARIO = 20;
  public static final int LLAVE_CERRADA = 8;
  public static final int INICIO_RESPUESTAS = 11;
  public static final int MODIFICAR_USUARIO = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MENOR_QUE",
  "MAYOR_QUE",
  "SIGNO_INTERROGACION",
  "DOS_PUNTOS",
  "COMA",
  "LLAVE_ABIERTA",
  "LLAVE_CERRADA",
  "INICIO_RESPUESTA",
  "FIN_RESPUESTA",
  "INICIO_RESPUESTAS",
  "FIN_RESPUESTAS",
  "INFO",
  "CREAR_USUARIO",
  "MODIFICAR_USUARIO",
  "ELIMINAR_USUARIO",
  "LOGIN_USUARIO",
  "NUEVO_FORMULARIO",
  "ELIMINAR_FORMULARIO",
  "MODIFICAR_FORMULARIO",
  "AGREGAR_COMPONENTE",
  "ELIMINAR_COMPONENTE",
  "MODIFICAR_COMPONENTE",
  "ERROR_PARAMETRO",
  "CUALQUIER_COSA_CON_ESPACIOS",
  "CUALQUIER_COSA_SIN_ESPACIOS"
  };
}

