
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package formulario;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPCIONES_PARAMETRO = 28;
  public static final int ALINEACION = 20;
  public static final int TEMA_PARAMETRO = 11;
  public static final int NOMBRE = 6;
  public static final int DOS_PUNTOS = 2;
  public static final int ESTRUCTURA = 25;
  public static final int INDICE = 18;
  public static final int FECHA = 34;
  public static final int PARENTESIS_ABIERTO = 26;
  public static final int LLAVE_ABIERTA = 12;
  public static final int TITULO = 5;
  public static final int ALINEACION_PARAMETRO = 21;
  public static final int FORMULARIO = 15;
  public static final int CLASE_PARAMETRO = 17;
  public static final int ID = 9;
  public static final int EOF = 0;
  public static final int CLASE = 16;
  public static final int CUALQUIER_COSA_CON_ESPACIOS = 36;
  public static final int CUALQUIER_COSA_SIN_ESPACIOS = 35;
  public static final int error = 1;
  public static final int DIGITO = 32;
  public static final int COMA = 3;
  public static final int URL = 31;
  public static final int ID_PARAMETRO = 10;
  public static final int FECHA_CREACION = 33;
  public static final int USUARIO_CREACION = 8;
  public static final int TEMA = 7;
  public static final int ID_FORMULARIO = 4;
  public static final int REQUERIDO = 22;
  public static final int NOMBRE_CAMPO = 14;
  public static final int PARENTESIS_CERRADO = 27;
  public static final int LLAVE_CERRADA = 13;
  public static final int COLUMNAS = 30;
  public static final int FILAS = 29;
  public static final int REQUERIDO_PARAMETRO = 23;
  public static final int TEXTO_VISIBLE = 19;
  public static final int OPCIONES = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOS_PUNTOS",
  "COMA",
  "ID_FORMULARIO",
  "TITULO",
  "NOMBRE",
  "TEMA",
  "USUARIO_CREACION",
  "ID",
  "ID_PARAMETRO",
  "TEMA_PARAMETRO",
  "LLAVE_ABIERTA",
  "LLAVE_CERRADA",
  "NOMBRE_CAMPO",
  "FORMULARIO",
  "CLASE",
  "CLASE_PARAMETRO",
  "INDICE",
  "TEXTO_VISIBLE",
  "ALINEACION",
  "ALINEACION_PARAMETRO",
  "REQUERIDO",
  "REQUERIDO_PARAMETRO",
  "OPCIONES",
  "ESTRUCTURA",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "OPCIONES_PARAMETRO",
  "FILAS",
  "COLUMNAS",
  "URL",
  "DIGITO",
  "FECHA_CREACION",
  "FECHA",
  "CUALQUIER_COSA_SIN_ESPACIOS",
  "CUALQUIER_COSA_CON_ESPACIOS"
  };
}

