
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package solicitudes;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETE_CERRADO = 17;
  public static final int USUARIO_ANTIGUO = 36;
  public static final int CUALQUIER_COSA_SIN_ESPACIOS = 71;
  public static final int CONSULTAR_DATOS = 30;
  public static final int MENOR_QUE = 3;
  public static final int MODIFICAR_FORMULARIO = 24;
  public static final int TITULO = 41;
  public static final int FIN_SOLICITUDES = 11;
  public static final int CORCHETE_ABIERTO = 16;
  public static final int USUARIO_NUEVO = 37;
  public static final int FECHA_MODIFICACION = 39;
  public static final int USUARIO_CREACION = 44;
  public static final int TEMA = 43;
  public static final int ELIMINAR_COMPONENTE = 27;
  public static final int CLASE_PARAMETRO = 50;
  public static final int PASSWORD = 33;
  public static final int OPCIONES = 57;
  public static final int MAYOR_QUE = 4;
  public static final int MODIFICAR_USUARIO = 18;
  public static final int TEMA_PARAMETRO = 46;
  public static final int SIGNO_INTERROGACION = 5;
  public static final int ELIMINAR_USUARIO = 19;
  public static final int TEXTO_VISIBLE = 52;
  public static final int DOS_PUNTOS = 8;
  public static final int GION = 69;
  public static final int CREAR_USUARIO = 12;
  public static final int FILAS = 59;
  public static final int NUEVO_PASSWORD = 38;
  public static final int FORMULARIO = 48;
  public static final int CUALQUIER_COSA_SIN_ESPACIOS_SIN_COMILLAS = 74;
  public static final int ELIMINAR_FORMULARIO = 23;
  public static final int SELECT = 62;
  public static final int REQUERIDO_PARAMETRO = 56;
  public static final int COMA = 9;
  public static final int DIGITO = 76;
  public static final int INICIO_SOLICITUD = 6;
  public static final int IGUAL = 66;
  public static final int FECHA = 35;
  public static final int CUALQUIER_COSA_REPORTE = 75;
  public static final int CLASE = 49;
  public static final int NOMBRE = 42;
  public static final int NOMBRE_CAMPO = 47;
  public static final int CONSULTA = 70;
  public static final int NUEVO_FORMULARIO = 22;
  public static final int LLAVE_CERRADA = 14;
  public static final int LOGIN_USUARIO = 20;
  public static final int COLUMNAS = 60;
  public static final int FIN_SOLICITUD = 7;
  public static final int CUALQUIER_COSA_CON_ESPACIOS = 72;
  public static final int OPERADOR_LOGICO = 67;
  public static final int USUARIO = 32;
  public static final int CONSULTAS = 29;
  public static final int URL = 61;
  public static final int FORM = 64;
  public static final int PARAMETROS_COMPONENTE = 25;
  public static final int EOF = 0;
  public static final int WHERE = 65;
  public static final int LLAVE_ABIERTA = 13;
  public static final int MODIFICAR_COMPONENTE = 28;
  public static final int OPCIONES_PARAMETRO = 73;
  public static final int COMILLA = 2;
  public static final int error = 1;
  public static final int CREDENCIALES_USUARIO = 15;
  public static final int ID_PARAMETRO = 34;
  public static final int ID = 40;
  public static final int OPERADOR_O = 58;
  public static final int FECHA_CREACION = 31;
  public static final int REQUERIDO = 55;
  public static final int PARAMETROS_FORMULARIO = 21;
  public static final int INICIO_SOLICITUDES = 10;
  public static final int CADENA = 45;
  public static final int INDICE = 51;
  public static final int ALINEACION = 53;
  public static final int OPERADOR_REPORTE = 68;
  public static final int TO = 63;
  public static final int AGREGAR_COMPONENTE = 26;
  public static final int ALINEACION_PARAMETRO = 54;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMILLA",
  "MENOR_QUE",
  "MAYOR_QUE",
  "SIGNO_INTERROGACION",
  "INICIO_SOLICITUD",
  "FIN_SOLICITUD",
  "DOS_PUNTOS",
  "COMA",
  "INICIO_SOLICITUDES",
  "FIN_SOLICITUDES",
  "CREAR_USUARIO",
  "LLAVE_ABIERTA",
  "LLAVE_CERRADA",
  "CREDENCIALES_USUARIO",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "MODIFICAR_USUARIO",
  "ELIMINAR_USUARIO",
  "LOGIN_USUARIO",
  "PARAMETROS_FORMULARIO",
  "NUEVO_FORMULARIO",
  "ELIMINAR_FORMULARIO",
  "MODIFICAR_FORMULARIO",
  "PARAMETROS_COMPONENTE",
  "AGREGAR_COMPONENTE",
  "ELIMINAR_COMPONENTE",
  "MODIFICAR_COMPONENTE",
  "CONSULTAS",
  "CONSULTAR_DATOS",
  "FECHA_CREACION",
  "USUARIO",
  "PASSWORD",
  "ID_PARAMETRO",
  "FECHA",
  "USUARIO_ANTIGUO",
  "USUARIO_NUEVO",
  "NUEVO_PASSWORD",
  "FECHA_MODIFICACION",
  "ID",
  "TITULO",
  "NOMBRE",
  "TEMA",
  "USUARIO_CREACION",
  "CADENA",
  "TEMA_PARAMETRO",
  "NOMBRE_CAMPO",
  "FORMULARIO",
  "CLASE",
  "CLASE_PARAMETRO",
  "INDICE",
  "TEXTO_VISIBLE",
  "ALINEACION",
  "ALINEACION_PARAMETRO",
  "REQUERIDO",
  "REQUERIDO_PARAMETRO",
  "OPCIONES",
  "OPERADOR_O",
  "FILAS",
  "COLUMNAS",
  "URL",
  "SELECT",
  "TO",
  "FORM",
  "WHERE",
  "IGUAL",
  "OPERADOR_LOGICO",
  "OPERADOR_REPORTE",
  "GION",
  "CONSULTA",
  "CUALQUIER_COSA_SIN_ESPACIOS",
  "CUALQUIER_COSA_CON_ESPACIOS",
  "OPCIONES_PARAMETRO",
  "CUALQUIER_COSA_SIN_ESPACIOS_SIN_COMILLAS",
  "CUALQUIER_COSA_REPORTE",
  "DIGITO"
  };
}

